# Generated by Django 2.2 on 2019-05-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('question', models.CharField(default='', max_length=200)),
                ('explanation', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
