# Generated by Django 2.2 on 2019-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0004_auto_20190430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=200),
        ),
    ]
