# Generated by Django 2.2 on 2019-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0005_auto_20190430_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='', max_length=300),
        ),
    ]
