# Generated by Django 2.2.1 on 2019-05-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0006_auto_20190430_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
